### ISSUE TITLE
Suggestions for implementation in your README file

### ISSUE THREAD

**Issue by Stavoh** [MaximKuryachiy/maximkuryachiy.github.io#1]
Hi Maxim
Thanks for guarding us!
I want to let you know about these tricks to make your text more entertaining:
1. Use double asterisks in both sides of a word or a sentence to make it **Bold**.
2. Use underscore in both sides of a word or a sentence to make it _Italic_.
Good luck!

**Comment by MaximKuryachiy** [comment]
Hello!
Of course, at your service :)
I updated the README file as you suggested, thank you for the feedback!
