### ISSUE TITLE
a comment

### ISSUE THREAD

**Issue by AnastasiiaMamaeva** [MaximKuryachiy/maximkuryachiy.github.io#2]
Really nice website!
I would suggest you, however, to change the size of image: it seems to be too wide. You can do it in photoshop or without any changes of photo using HTML code: https://www.w3schools.com/tags/att_img_width.asp
Good luck!

**Comment by MaximKuryachiy** [comment]
Thank you!
Also thanks for the useful link.
I have changed the formatting of the image a bit, so it may look better now :)

**Comment by LiorLin** [comment]
Hi Maxim, 
Nice web ! It seems like the link you provided is not connected to the article's title as you intended. 
Probably just a typo in the markdown. 
Lior

@hadarklimovski

**Comment by MaximKuryachiy** [comment]
> Hi Maxim, Nice web ! It seems like the link you provided is not connected to the article's title as you intended. Probably just a typo in the markdown. Lior
> 
> @HadarKlimovski

Hello, thank you! Now fixed :)

**Comment by AnastasiiaMamaeva** [comment]
@liroh99
